### ISSUE TITLE
Flubbr Activity leaks ServiceConnection.

### ISSUE THREAD

**Issue by CptFoobar** [TigerKid001/Flubbr#4]
The Flubbr activity leaks the ServiceConnection for PluginManager. Stacktrace:

```
02-09 18:12:25.413  25611-25611/tigerkid.applab.Flubbr E/ActivityThread﹕ Activity tigerkid.applab.Flubbr.Flubbr has leaked ServiceConnection tigerkid.applab.Flubbr.Flubbr$PMServiceConnection@41ef8800 that was originally bound here
    android.app.ServiceConnectionLeaked: Activity tigerkid.applab.Flubbr.Flubbr has leaked ServiceConnection tigerkid.applab.Flubbr.Flubbr$PMServiceConnection@41ef8800 that was originally bound here
            at android.app.LoadedApk$ServiceDispatcher.<init>(LoadedApk.java:965)
            at android.app.LoadedApk.getServiceDispatcher(LoadedApk.java:859)
            at android.app.ContextImpl.bindService(ContextImpl.java:1313)
            at android.app.ContextImpl.bindService(ContextImpl.java:1305)
            at android.content.ContextWrapper.bindService(ContextWrapper.java:405)
            at tigerkid.applab.Flubbr.Flubbr.bindPluginManager(Flubbr.java:115)
            at tigerkid.applab.Flubbr.Flubbr.onCreate(Flubbr.java:84)
            at android.app.Activity.performCreate(Activity.java:5203)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1094)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2078)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2139)
            at android.app.ActivityThread.access$700(ActivityThread.java:143)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1241)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:4960)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1038)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:805)
            at dalvik.system.NativeStart.main(Native Method)
02-09 18:12:25.423  25611-25611/tigerkid.applab.Flubbr D/AndroidRuntime﹕ Shutting down VM
02-09 18:12:25.423  25611-25611/tigerkid.applab.Flubbr W/dalvikvm﹕ threadid=1: thread exiting with uncaught exception (group=0x41455468)
02-09 18:12:25.423  25611-25611/tigerkid.applab.Flubbr E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.RuntimeException: Unable to stop service tigerkid.applab.Flubbr.PluginManager@41efd188: java.lang.NullPointerException
            at android.app.ActivityThread.handleStopService(ActivityThread.java:2605)
            at android.app.ActivityThread.access$2100(ActivityThread.java:143)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1343)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:4960)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1038)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:805)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.NullPointerException
            at tigerkid.applab.Flubbr.PluginManager.releaseOpService(PluginManager.java:123)
            at tigerkid.applab.Flubbr.PluginManager.onDestroy(PluginManager.java:71)
            at android.app.ActivityThread.handleStopService(ActivityThread.java:2588)
            at android.app.ActivityThread.access$2100(ActivityThread.java:143)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1343)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:4960)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1038)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:805)
            at dalvik.system.NativeStart.main(Native Method)
```

**Comment by CptFoobar** [comment]
Fixed in 6bad6815c5ed8a9ec165b01952ecebcecd56961f.
